---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
```{r}
library(readr)
library(quantmod)
library(xts)
library(PerformanceAnalytics)
library(rugarch)
library(FinTS)
library(e1071)
library(tseries)
library(rmgarch)
```

```{r}
startDate = as.Date("2017-11-27") 
endDate = as.Date("2022-11-25")
getSymbols("MSFT", from = startDate, to = endDate)
```

```{r}
chartSeries(MSFT)
```
```{r}
# Daily returns
return_MSFT <- CalculateReturns(MSFT$MSFT.Adjusted)
return_MSFT <- return_MSFT[-1]
chartSeries(return_MSFT, theme = 'white')
chart.Histogram(return_MSFT,
                methods = c('add.density','add.normal'),
                colorset = c('blue','green','red'))
# Green line is higher than normal distribution (red line). Hence, student t distribution (heavier tail) would be more suitable for model
```


```{r}
MSFT_garch_1 <- ugarchspec(mean.model = list(armaOrder=c(0,1)),
                          variance.model = list(model = 'sGARCH',
                                                garchOrder = c(1,1)),
                          distribution = 'std') # standard GARCH model
MSFT_fit_garch_1 <- ugarchfit(spec = MSFT_garch_1,
                              data = na.omit(return_MSFT))
#infocriteria(MSFT_fit_garch_1)
MSFT_fit_garch_1
infocriteria(MSFT_fit_garch_1)
#coef(MSFT_fit_garch_1)
```

```{r}
MSFT_garch_2 <- ugarchspec(mean.model = list(armaOrder = c(0,1)),
                           variance.model = list(model = "sGARCH",
                                                 garchOrder = c(1,2)),
                           distribution = 'std')
MSFT_fit_garch_2 <- ugarchfit(spec = MSFT_garch_2,
                              data = na.omit(return_MSFT))
# MSFT_fit_garch_2
infocriteria(MSFT_fit_garch_2)
#coef(MSFT_fit_garch_2)
```


```{r}
MSFT_garch_3 <- ugarchspec(mean.model = list(armaOrder=c(0,1)),
                           variance.model = list(model = 'sGARCH', 
                                                 garchOrder = c(1,3)),
                           distribution = 'std')

MSFT_fit_garch_3 <- ugarchfit(spec = MSFT_garch_3, data = na.omit(return_MSFT))
#MSFT_fit_garch_3
infocriteria(MSFT_fit_garch_3)
#coef(MSFT_fit_garch_3)
```

```{r}
MSFT_garch_4 <- ugarchspec(mean.model = list(armaOrder=c(0,01)),
                           variance.model = list(model = 'sGARCH', 
                                                 garchOrder = c(2,1)),
                           distribution = 'std')

MSFT_fit_garch_4 <- ugarchfit(spec = MSFT_garch_4, data = na.omit(return_MSFT))
#MSFT_fit_garch_4
infocriteria(MSFT_fit_garch_4)
#coef(MSFT_fit_garch_4)
```
```{r}
MSFT_garch_5 <- ugarchspec(mean.model = list(armaOrder=c(0,1)),
                           variance.model = list(model = 'sGARCH', 
                                                 garchOrder = c(2,2)),
                           distribution = 'std')

MSFT_fit_garch_5 <- ugarchfit(spec = MSFT_garch_5, data = na.omit(return_MSFT))
#MSFT_fit_garch_5
infocriteria(MSFT_fit_garch_5)
#coef(MSFT_fit_garch_5)
```

```{r}
MSFT_garch_6 <- ugarchspec(mean.model = list(armaOrder=c(0,0)),
                           variance.model = list(model = 'sGARCH', 
                                                 garchOrder = c(1,1)),
                           distribution = 'std')

MSFT_fit_garch_6 <- ugarchfit(spec = MSFT_garch_6, data = na.omit(return_MSFT))
#MSFT_fit_garch_6
infocriteria(MSFT_fit_garch_6)
#coef(MSFT_fit_garch_6)
```

```{r}
MSFT_forecast <- ugarchforecast(MSFT_fit_garch_1,
                                 data = na.omit(return_MSFT),
                                 n.ahead = 20)
MSFT_forecast
```

```{r}
MSFT_fit_roll <- ugarchfit(MSFT_garch_1,
                           data = na.omit(return_MSFT),
                           out.sample = 500)
MSFT_fore_roll <- ugarchforecast(MSFT_fit_roll, 
                                 n.ahead = 20,
                                 n.roll=50)
MSFT_fore_roll
par(mfrow = c(1,2))
plot(MSFT_fore_roll, which=1)
plot(MSFT_fore_roll, which=2)
plot(MSFT_fore_roll, which='all')
```


```{r}
# We chose model with lowest AIC and Information Criteria
s <- MSFT_garch_1
m <- MSFT_fit_garch_1
#Merge parameter
sfinal <- s
setfixed(sfinal) <- as.list(coef(m))

f2021 <- ugarchforecast(data = na.omit(return_MSFT["/2021-12"]),
                        fitORspec = sfinal,
                        n.ahead = 252)
f2022 <- ugarchforecast(data = na.omit(return_MSFT["/2022-12"]),
                        fitORspec = sfinal,
                        n.ahead = 252)
#Forecasting future variance
par(mfrow=c(1,1))
plot(sigma(f2021))
plot(sigma(f2022))

sim <- ugarchpath(spec = sfinal,
                  m.sim = 3,
                  n.sim = 1*252,
                  rseed = 123)
plot.zoo(fitted(sim))
plot.zoo(sigma(sim))
p <- 247.49	*apply(fitted(sim),2,'cumsum')+247.49	
matplot(p, type = "l", lwd=3)
```




